deployer_web_queue:
    pattern:  /queue
    defaults: { _controller: DeployerWebBundle:Web:queue }

deployer_webhook_gitlab:
    pattern:  /webhook/gitlab
    defaults: { _controller: DeployerWebBundle:Webhook:gitlab }
